# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

arma_cmf <- function(x, M, y, maxIter, stableLag, critval, decfun, nCores, nStarts, pb) {
    .Call(`_cmfilter_arma_cmf`, x, M, y, maxIter, stableLag, critval, decfun, nCores, nStarts, pb)
}

checkOMP <- function() {
    .Call(`_cmfilter_checkOMP`)
}

